/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Donation = IDL.Record({
  'message' : IDL.Text,
  'amount' : IDL.Nat,
  'donor' : IDL.Principal,
});
export const Tier = IDL.Record({ 'tierName' : IDL.Text, 'priceICP' : IDL.Nat });
export const MonetizationStatus = IDL.Record({
  'enabled' : IDL.Bool,
  'subscriberCount' : IDL.Nat,
});
export const Membership = IDL.Record({
  'tierName' : IDL.Text,
  'priceICP' : IDL.Nat,
  'channel' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'disableMonetization' : IDL.Func([], [], []),
  'enableMonetization' : IDL.Func([], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDonationsByVideo' : IDL.Func([IDL.Text], [IDL.Vec(Donation)], ['query']),
  'getMembershipTiers' : IDL.Func([IDL.Principal], [IDL.Vec(Tier)], ['query']),
  'getMonetizationStatus' : IDL.Func(
      [IDL.Principal],
      [MonetizationStatus],
      ['query'],
    ),
  'getMyMemberships' : IDL.Func([], [IDL.Vec(Membership)], ['query']),
  'getTierMembers' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinMembership' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'setMembershipTiers' : IDL.Func([IDL.Vec(Tier)], [], []),
  'storeDonation' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Donation = IDL.Record({
    'message' : IDL.Text,
    'amount' : IDL.Nat,
    'donor' : IDL.Principal,
  });
  const Tier = IDL.Record({ 'tierName' : IDL.Text, 'priceICP' : IDL.Nat });
  const MonetizationStatus = IDL.Record({
    'enabled' : IDL.Bool,
    'subscriberCount' : IDL.Nat,
  });
  const Membership = IDL.Record({
    'tierName' : IDL.Text,
    'priceICP' : IDL.Nat,
    'channel' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'disableMonetization' : IDL.Func([], [], []),
    'enableMonetization' : IDL.Func([], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDonationsByVideo' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Donation)],
        ['query'],
      ),
    'getMembershipTiers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Tier)],
        ['query'],
      ),
    'getMonetizationStatus' : IDL.Func(
        [IDL.Principal],
        [MonetizationStatus],
        ['query'],
      ),
    'getMyMemberships' : IDL.Func([], [IDL.Vec(Membership)], ['query']),
    'getTierMembers' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinMembership' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'setMembershipTiers' : IDL.Func([IDL.Vec(Tier)], [], []),
    'storeDonation' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };