/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Donation {
    message: string;
    amount: bigint;
    donor: Principal;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface MonetizationStatus {
    enabled: boolean;
    subscriberCount: bigint;
}
export interface Membership {
    tierName: string;
    priceICP: bigint;
    channel: Principal;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Tier {
    tierName: string;
    priceICP: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    disableMonetization(): Promise<void>;
    enableMonetization(): Promise<void>;
    getCallerUserRole(): Promise<UserRole>;
    getDonationsByVideo(videoId: string): Promise<Array<Donation>>;
    getMembershipTiers(channel: Principal): Promise<Array<Tier>>;
    getMonetizationStatus(user: Principal): Promise<MonetizationStatus>;
    getMyMemberships(): Promise<Array<Membership>>;
    getTierMembers(channel: Principal, tierName: string): Promise<Array<Principal>>;
    isCallerAdmin(): Promise<boolean>;
    joinMembership(channel: Principal, tierName: string): Promise<void>;
    setMembershipTiers(tiers: Array<Tier>): Promise<void>;
    storeDonation(videoId: string, message: string, amount: bigint): Promise<void>;
    getAllVideos(): Promise<Array<any>>;
    getTrendingVideos(): Promise<Array<any>>;
    getVideo(videoId: string): Promise<any | null>;
    getVideosByCategory(category: string): Promise<Array<any>>;
    getVideosByUploader(uploader: any): Promise<Array<any>>;
    getCategories(): Promise<Array<string>>;
    incrementView(videoId: string): Promise<void>;
    toggleLike(videoId: string): Promise<void>;
    searchVideos(keyword: string): Promise<Array<any>>;
    addComment(videoId: string, text: string): Promise<void>;
    getCommentsByVideo(videoId: string): Promise<Array<any>>;
    getChannelProfile(user: any): Promise<any | null>;
    updateChannelProfile(username: string, bio: string): Promise<void>;
    getCallerUserProfile(): Promise<any | null>;
    saveCallerUserProfile(profile: any): Promise<void>;
    subscribeChannel(uploader: any): Promise<void>;
    unsubscribeChannel(uploader: any): Promise<void>;
    uploadVideo(title: string, description: string, category: string, thumbnailBlobId: string, videoBlobId: string): Promise<void>;
}
import type { UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";

const _store = {
  videos: [
    { id: "v1", title: "Pathaan - Full Movie Review", description: "Shah Rukh Khan returns in this action-packed blockbuster!", category: "Bollywood", uploader: { toText: () => "aaaaa-aa" } as any, thumbnailBlobId: "", videoBlobId: "", viewCount: 125000n, likeCount: 8400n, createdAt: BigInt(Date.now()) },
    { id: "v2", title: "India vs Australia - 4th Test Highlights", description: "Thrilling final day action from the Test series.", category: "Cricket", uploader: { toText: () => "aaaaa-aa" } as any, thumbnailBlobId: "", videoBlobId: "", viewCount: 340000n, likeCount: 21000n, createdAt: BigInt(Date.now()) },
    { id: "v3", title: "Mumbai Street Food Tour 2025", description: "Best vada pav, pav bhaji, and more from the streets of Mumbai.", category: "Food", uploader: { toText: () => "aaaaa-aa" } as any, thumbnailBlobId: "", videoBlobId: "", viewCount: 78000n, likeCount: 5200n, createdAt: BigInt(Date.now()) },
    { id: "v4", title: "Zakir Khan - Sakht Launda 3", description: "The funniest stand-up special yet!", category: "Comedy", uploader: { toText: () => "aaaaa-aa" } as any, thumbnailBlobId: "", videoBlobId: "", viewCount: 890000n, likeCount: 62000n, createdAt: BigInt(Date.now()) },
    { id: "v5", title: "Raga Yaman on Sitar - Classical Evening", description: "Peaceful sitar recital featuring Raga Yaman.", category: "Music", uploader: { toText: () => "aaaaa-aa" } as any, thumbnailBlobId: "", videoBlobId: "", viewCount: 45000n, likeCount: 3100n, createdAt: BigInt(Date.now()) },
    { id: "v6", title: "Diwali Special Bhajan - Om Jai Jagdish", description: "Devotional singing for the festival of lights.", category: "Devotional", uploader: { toText: () => "aaaaa-aa" } as any, thumbnailBlobId: "", videoBlobId: "", viewCount: 220000n, likeCount: 15000n, createdAt: BigInt(Date.now()) },
  ] as any[],
  comments: {} as Record<string, any[]>,
  channels: {} as Record<string, any>,
  userProfiles: {} as Record<string, any>,
  likes: {} as Record<string, Set<string>>,
  subscriptions: {} as Record<string, Set<string>>,
  monetization: {} as Record<string, boolean>,
};

export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async disableMonetization(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.disableMonetization();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.disableMonetization();
            return result;
        }
    }
    async enableMonetization(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.enableMonetization();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enableMonetization();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDonationsByVideo(arg0: string): Promise<Array<Donation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDonationsByVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDonationsByVideo(arg0);
            return result;
        }
    }
    async getMembershipTiers(arg0: Principal): Promise<Array<Tier>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMembershipTiers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMembershipTiers(arg0);
            return result;
        }
    }
    async getMonetizationStatus(arg0: Principal): Promise<MonetizationStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonetizationStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonetizationStatus(arg0);
            return result;
        }
    }
    async getMyMemberships(): Promise<Array<Membership>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyMemberships();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyMemberships();
            return result;
        }
    }
    async getTierMembers(arg0: Principal, arg1: string): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTierMembers(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTierMembers(arg0, arg1);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinMembership(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinMembership(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinMembership(arg0, arg1);
            return result;
        }
    }
    async setMembershipTiers(arg0: Array<Tier>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMembershipTiers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMembershipTiers(arg0);
            return result;
        }
    }
    async storeDonation(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.storeDonation(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeDonation(arg0, arg1, arg2);
            return result;
        }
    }

    async getAllVideos() { return [..._store.videos]; }
    async getTrendingVideos() { return [..._store.videos].sort((a, b) => Number(b.viewCount - a.viewCount)); }
    async getVideo(videoId: string) { return _store.videos.find(v => v.id === videoId) ?? null; }
    async getVideosByCategory(category: string) { return _store.videos.filter(v => v.category === category); }
    async getVideosByUploader(uploader: any) { return _store.videos.filter(v => v.uploader.toText() === uploader.toText()); }
    async getCategories() { return ["Bollywood", "Cricket", "Music", "Comedy", "Food", "Devotional", "News", "Education", "Entertainment"]; }
    async incrementView(videoId: string) { const v = _store.videos.find(v => v.id === videoId); if (v) v.viewCount += 1n; }
    async toggleLike(videoId: string) { const v = _store.videos.find(v => v.id === videoId); if (v) v.likeCount += 1n; }
    async searchVideos(keyword: string) { const k = keyword.toLowerCase(); return _store.videos.filter(v => v.title.toLowerCase().includes(k)); }
    async addComment(videoId: string, text: string) { if (!_store.comments[videoId]) _store.comments[videoId] = []; _store.comments[videoId].push({ id: `c${Date.now()}`, videoId, commenter: { toText: () => "user" } as any, text, createdAt: BigInt(Date.now()) }); }
    async getCommentsByVideo(videoId: string) { return _store.comments[videoId] ?? []; }
    async getChannelProfile(user: any) { const key = user.toText(); return _store.channels[key] ?? { username: "DesiCreator", bio: "Creating content for India!", subscriberCount: 42n }; }
    async updateChannelProfile(_username: string, _bio: string) { }
    async getCallerUserProfile() { return { username: "DesiUser", bio: "Namaste!" }; }
    async saveCallerUserProfile(_profile: any) { }
    async subscribeChannel(uploader: any) { const key = uploader.toText(); if (!_store.channels[key]) _store.channels[key] = { username: "DesiCreator", bio: "", subscriberCount: 42n }; _store.channels[key].subscriberCount += 1n; }
    async unsubscribeChannel(uploader: any) { const key = uploader.toText(); if (_store.channels[key] && _store.channels[key].subscriberCount > 0n) _store.channels[key].subscriberCount -= 1n; }
    async uploadVideo(title: string, description: string, category: string, thumbnailBlobId: string, videoBlobId: string) { _store.videos.push({ id: `v${Date.now()}`, title, description, category, uploader: { toText: () => "user" } as any, thumbnailBlobId, videoBlobId, viewCount: 0n, likeCount: 0n, createdAt: BigInt(Date.now()) }); }
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
